/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import RemoteNodes.MinerListener;
import RemoteNodes.NodeListener;
import RemoteNodes.RemoteVotingI;
import RemoteNodes.RemoteVotingObject;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.rmi.RemoteException;
import java.security.Key;
import java.security.KeyPair;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utils.GuiUtils;
import utils.RMI;
import utils.SecurityUtils;
import utils.Session;

/**
 *
 * @author Acer
 */
public class NodeP2P extends javax.swing.JFrame implements NodeListener, MinerListener {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NodeP2P.class.getName());
    RemoteVotingObject myremoteObject;
    private Key aes;
    private KeyPair rsa;
    /**
     * Creates new form Node
     */
    public NodeP2P() {
        initComponents();

        txtServerListeningObjectName.setText(RemoteVotingObject.REMOTE_OBJECT_NAME);

        setRandomPosition(); // aqui é onde provavelmente crias o myremoteObject

        if (myremoteObject != null && myremoteObject.miner != null) {
            myremoteObject.miner.addListener(this);
        }

        updateUserInfo();
    }

    private void setRandomPosition() {
        //:::: Mover a janela para uma posição aleatório
        this.setSize(845, 595);
        // Obter a resolução do ecrã
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        // Gerar posição aleatória garantindo que a janela cabe no ecrã
        Random r = new Random();
        int x = r.nextInt(screenSize.width - this.getWidth());
        int y = r.nextInt(screenSize.height - this.getHeight());
        // Colocar a janela na posição aleatória
        setLocation(x, y);
        txtServerListeningPort.setText("1000" + r.nextInt(10));
        btStartServerActionPerformed(null);
        btConnectActionPerformed(null);
    }

    private void updateUserInfo() {
        if (!Session.isLoggedIn()) {
            lblUserInfo.setText("Não autenticado");
            return;
        }
        
        

        Session.Keys k = Session.get();
        String voterId = shortId(k.publicKey.getEncoded());
        userNameField.setText(k.username);
        userNameField.setEditable(false);
        lblUserInfo.setText("User: " + k.username + " | VoterID: " + voterId);
    }

    private static String shortId(byte[] data) {
        try {
            java.security.MessageDigest md = java.security.MessageDigest.getInstance("SHA-256");
            byte[] h = md.digest(data);

            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < 8; i++) {
                sb.append(String.format("%02x", h[i]));
            }
            return sb.toString();
        } catch (Exception e) {
            return "erro";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpMain = new javax.swing.JTabbedPane();
        pnServer = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btStartServer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtServerListeningPort = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtServerListeningObjectName = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtServerLog = new javax.swing.JTextPane();
        pnNetwork = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtNetwork = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        btConnect = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNodeAddress = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        userNameField = new javax.swing.JTextField();
        partidosOptions = new javax.swing.JComboBox<>();
        voteBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblUserInfo = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        hashesList = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btStartServer.setText("Start");
        btStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartServerActionPerformed(evt);
            }
        });

        jLabel1.setText("Port Number");

        jScrollPane2.setViewportView(txtServerListeningPort);

        jScrollPane3.setViewportView(txtServerListeningObjectName);

        jLabel2.setText("ObjectName");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btStartServer, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 246, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btStartServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(txtServerLog);

        javax.swing.GroupLayout pnServerLayout = new javax.swing.GroupLayout(pnServer);
        pnServer.setLayout(pnServerLayout);
        pnServerLayout.setHorizontalGroup(
            pnServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnServerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnServerLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnServerLayout.setVerticalGroup(
            pnServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnServerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE))
        );

        tpMain.addTab("Server", pnServer);

        txtNetwork.setColumns(20);
        txtNetwork.setRows(5);
        jScrollPane4.setViewportView(txtNetwork);

        btConnect.setText("Connect");
        btConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConnectActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        txtNodeAddress.setText("jTextField1");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNodeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNodeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btConnect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnNetworkLayout = new javax.swing.GroupLayout(pnNetwork);
        pnNetwork.setLayout(pnNetworkLayout);
        pnNetworkLayout.setHorizontalGroup(
            pnNetworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNetworkLayout.createSequentialGroup()
                .addGroup(pnNetworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNetworkLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnNetworkLayout.setVerticalGroup(
            pnNetworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNetworkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpMain.addTab("Connect", pnNetwork);

        userNameField.setText("jTextField1");

        partidosOptions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "E-Ergue-se", "ADN-Alternativa democrática Nacional", "PTP- Partilho Trabalhador Portugues", "PPD", "PSD", "CDS", "PPPPM-ALIANCA DEMOCRATICA", "BE- Bloco de Esquerda", "IL- Iniciativa Liberal", "JPP- Juntos pelo Povo", "MAS-Movimento Arternativa Socialista", "PS=Partido Socialista", "CH-CHEGA", "ND-Nova Direita", "PCTP/MRPP-Partido Comunista dos Trabalhadores Portugueses", "L-Livre", "PAN-PESSOAS ANIMAIS NATUREZA" }));
        partidosOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partidosOptionsActionPerformed(evt);
            }
        });

        voteBtn.setText("Votar!");
        voteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voteBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("jLabel1");

        lblUserInfo.setText("Não Autenticado");

        hashesList.setColumns(20);
        hashesList.setRows(5);
        jScrollPane5.setViewportView(hashesList);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane5)
                            .addComponent(userNameField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(partidosOptions, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUserInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(voteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(116, 116, 116)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblUserInfo)
                .addGap(27, 27, 27)
                .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(partidosOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 44, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(37, 37, 37))
        );

        lblUserInfo.getAccessibleContext().setAccessibleName("");

        tpMain.addTab("Vote", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpMain)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpMain)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voteBtnActionPerformed
        try {
            byte[] voterEncrypted = SecurityUtils.encrypt(userNameField.getText().getBytes(), aes);
            byte[] partidoEncrypted = SecurityUtils.encrypt(((String)partidosOptions.getSelectedItem()).getBytes(), aes);
            Session.Keys sKeys = Session.get();
            myremoteObject.vote(voterEncrypted, partidoEncrypted, sKeys.publicKey);
        } catch (RemoteException ex) {
            System.getLogger(NodeP2P.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (Exception ex) {
            System.getLogger(NodeP2P.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        
        
    }//GEN-LAST:event_voteBtnActionPerformed

    private void partidosOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partidosOptionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partidosOptionsActionPerformed

    private void btStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartServerActionPerformed
        try {
            //:::::::::: Objeto remoto  :::::::::::::::
            int port = Integer.parseInt(txtServerListeningPort.getText());
            String name = RemoteVotingObject.REMOTE_OBJECT_NAME;
            myremoteObject = new RemoteVotingObject(port, this);
            RMI.startRemoteObject(myremoteObject, port, name);
            //:::::::: GUI  ::::::::::::::::
            //this.setTitle(RMI.getRemoteName(port, name));
            this.txtNodeAddress.setText(RMI.getRemoteName(port, name));
            
            rsa = SecurityUtils.generateRSAKeyPair(2048);
            byte[] byteAes = myremoteObject.getAes(rsa.getPublic());
            byteAes = SecurityUtils.decrypt(byteAes, rsa.getPrivate());
            aes =SecurityUtils.getAESKey(byteAes);
            
        } catch (Exception ex) {
            onException(ex, "Starting server");
            Logger.getLogger(NodeP2P.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btStartServerActionPerformed

    private void btConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConnectActionPerformed
        // TODO add your handling code here:
        try {
            String address = txtNodeAddress.getText();
            RemoteVotingI node = (RemoteVotingI) RMI.getRemote(address);
            myremoteObject.addNode(node);
            System.out.println("ConnectedTo " + node.getAdress());
        } catch (Exception ex) {
            onException(ex, "connect");
            Logger.getLogger(NodeP2P.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btConnectActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            hashesList.setText("");
            for (String object : myremoteObject.getBlockHashes()) {
                hashesList.setText(hashesList.getText()+ object + "\n");
            }
        } catch (RemoteException ex) {
            System.getLogger(NodeP2P.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NodeP2P().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConnect;
    private javax.swing.JButton btStartServer;
    private javax.swing.JTextArea hashesList;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblUserInfo;
    private javax.swing.JComboBox<String> partidosOptions;
    private javax.swing.JPanel pnNetwork;
    private javax.swing.JPanel pnServer;
    private javax.swing.JTabbedPane tpMain;
    private javax.swing.JTextArea txtNetwork;
    private javax.swing.JTextField txtNodeAddress;
    private javax.swing.JTextPane txtServerListeningObjectName;
    private javax.swing.JTextPane txtServerListeningPort;
    private javax.swing.JTextPane txtServerLog;
    private javax.swing.JTextField userNameField;
    private javax.swing.JButton voteBtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onStart(String message) {
        //imgServerRunning.setEnabled(true);
        btStartServer.setEnabled(false);
        GuiUtils.addText(txtServerLog, "Start server", message);
    }

    @Override
    public void onConnect(String address) {
        try {
            List<RemoteVotingI> net = myremoteObject.getNetwork();
            String txt = "";
            for (RemoteVotingI iremoteP2P : net) {
                txt += iremoteP2P.getAdress() + "\n";
            }
            txtNetwork.setText(txt);
            tpMain.setSelectedComponent(pnNetwork);
            onTransaction("Syncronize to " + address);
        } catch (RemoteException ex) {
            onException(ex, "On conect");
            Logger.getLogger(NodeP2P.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void onException(Exception e, String title) {
        JOptionPane.showMessageDialog(this, e.getMessage(), title, JOptionPane.WARNING_MESSAGE);

    }

    @Override
    public void onTransaction(String transaction) {
        /*SwingUtilities.invokeLater(() -> {
            try {
                tpMain.setSelectedComponent(pnTransaction);
                txtLstTransactions.setText("Received : " + transaction + "\nTransactions:\n");
                for (String tr : myremoteObject.getTransactions()) {
                    txtLstTransactions.append(tr + "\n");

                }
            } catch (RemoteException ex) {
                onException(ex, "On Transaction");
                Logger.getLogger(NodeP2P.class.getName()).log(Level.SEVERE, null, ex);
            }
        });*/
    }

    @Override
    public void onStartMining(String message, int dificulty) {
        /*SwingUtilities.invokeLater(() -> {
            imgMiner.setVisible(true);
            imgWinner.setVisible(false);
            txtMinerMessage.setText(message);
        });*/

    }

    @Override
    public void onStopMining(int nonce) {
        /*SwingUtilities.invokeLater(() -> {
            try {
                imgMiner.setVisible(false);
                btStartMinig.setEnabled(true);
                txtNonce.setText("" + nonce);
                txtMinerMessage.setText(myremoteObject.getHash());

            } catch (Exception ex) {
                System.getLogger(NodeP2P.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });*/

    }

    @Override
    public void onNonceFound(int nonce) {
        /*SwingUtilities.invokeLater(() -> {
            try {            
                myremoteObject.stopMining(nonce);
            } catch (RemoteException ex) {
                System.getLogger(NodeP2P.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });*/
    }

}
